export const topCollections = [
    {
      "id": 1,
      "image": "/images/tc1.svg",
      "name": "Freak In Me",
      "author": "Tommy lee",
      "verified": true,
      "ethereum": "24,328.16",
      "changes": "+219.48%",
      "category": "Art",
    },
    {
      "id": 2,
      "image": "/images/tc2.svg",
      "category": "Art",
      "name": "Wonderful Tonight",
      "author": "Tommy lee",
      "verified": false,
      "ethereum": "24,328.16",
      "changes": "+219.48%",
    },
    {
      "id": 3,
      "image": "/images/tc3.svg",
      "category": "Art",
      "author": "Tommy lee",
      "verified": false,
      "name": "Mine",
      "author": "Tommy lee",
      "verified": false,
      "ethereum": "24,328.16",
      "changes": "+219.48%",
    },
    {
      "id": 4,
      "image": "/images/tc4.svg",
      "category": "Art",
      "author": "Tommy lee",
      "verified": false,
      "name": "Baby One More Time",
      "author": "Tommy lee",
      "verified": false,
      "ethereum": "24,328.16",
      "changes": "+219.48%",
    },
    {
      "id": 5,
      "image": "/images/tc5.svg",
      "category": "Art",
      "author": "Tommy lee",
      "verified": false,
      "name": "Baby Powder",
      "author": "Tommy lee",
      "verified": false,
      "ethereum": "24,328.16",
      "changes": "+219.48%",
    },
    {
      "id": 6,
      "image": "/images/tc1.svg",
      "name": "Freak In Me",
      "author": "Tommy lee",
      "verified": false,
      "ethereum": "24,328.16",
      "changes": "+219.48%",
      "category": "Art",
    },
    {
      "id": 7,
      "image": "/images/tc2.svg",
      "category": "Art",
      "name": "Wonderful Tonight",
      "author": "Tommy lee",
      "verified": false,
      "ethereum": "24,328.16",
      "changes": "+219.48%",
    },
    {
      "id": 8,
      "image": "/images/tc3.svg",
      "category": "Art",
      "author": "Tommy lee",
      "verified": false,
      "name": "Mine",
      "author": "Tommy lee",
      "verified": false,
      "ethereum": "24,328.16",
      "changes": "+219.48%",
    },
    {
      "id": 9,
      "image": "/images/tc4.svg",
      "category": "Art",
      "author": "Tommy lee",
      "verified": false,
      "name": "Baby One More Time",
      "author": "Tommy lee",
      "verified": false,
      "ethereum": "24,328.16",
      "changes": "+219.48%",
    },
    {
      "id": 10,
      "image": "/images/tc5.svg",
      "category": "Art",
      "author": "Tommy lee",
      "verified": false,
      "name": "Baby Powder",
      "author": "Tommy lee",
      "verified": false,
      "ethereum": "24,328.16",
      "changes": "+219.48%",
    }
  ]
  