export const userCollections = [
    {
        "id": 1,
        "category": "Art",
        "isVerified": true,
        "image": "/images/userCard1.svg",
        "productId": "#90329174",
        "price": "24,328",
        "name": "Tommy Project 01",
        "date": "17 hours left",
        "liked": 30,
    },
    {
        "id": 2,
        "category": "Art",
        "isVerified": true,
        "image": "/images/userCard2.svg",
        "productId": "#90329174",
        "price": "24,328",
        "name": "Tommy Project 01",
        "date": "17 hours left",
        "liked": 30,
    },
    {
        "id": 3,
        "category": "Art",
        "isVerified": true,
        "image": "/images/userCard3.svg",
        "productId": "#90329174",
        "price": "24,328",
        "name": "Tommy Project 01",
        "date": "17 hours left",
        "liked": 30,
    },
    {
        "id": 4,
        "category": "Art",
        "isVerified": true,
        "image": "/images/userCard4.svg",
        "productId": "#90329174",
        "price": "24,328",
        "name": "Tommy Project 01",
        "date": "17 hours left",
        "liked": 30,
    },
    {
        "id": 5,
        "category": "Art",
        "isVerified": true,
        "image": "/images/userCard5.svg",
        "productId": "#90329174",
        "price": "24,328",
        "name": "Tommy Project 01",
        "date": "17 hours left",
        "liked": 30,
    },
    {
        "id": 6,
        "category": "Art",
        "isVerified": true,
        "image": "/images/userCard6.svg",
        "productId": "#90329174",
        "price": "24,328",
        "name": "Tommy Project 01",
        "date": "17 hours left",
        "liked": 30,
    },
    {
        "id": 7,
        "category": "Art",
        "isVerified": true,
        "image": "/images/userCard7.svg",
        "productId": "#90329174",
        "price": "24,328",
        "name": "Tommy Project 01",
        "date": "17 hours left",
        "liked": 30,
    },
    {
        "id": 8,
        "category": "Art",
        "isVerified": true,
        "image": "/images/userCard8.svg",
        "productId": "#90329174",
        "price": "24,328",
        "name": "Tommy Project 01",
        "date": "17 hours left",
        "liked": 30,
    },
    {
        "id": 9,
        "category": "Art",
        "isVerified": true,
        "image": "/images/userCard9.svg",
        "productId": "#90329174",
        "price": "24,328",
        "name": "Tommy Project 01",
        "date": "17 hours left",
        "liked": 30,
    },
    {
        "id": 10,
        "category": "Art",
        "isVerified": true,
        "image": "/images/userCard10.svg",
        "productId": "#90329174",
        "price": "24,328",
        "name": "Tommy Project 01",
        "date": "17 hours left",
        "liked": 30,
    }
]
